---
apiVersion: v1
kind: Service
metadata:
  name: "brokerclient"
  labels:
    app: "brokerclient"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: "brokerclient"
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "brokerclient"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "brokerclient"
    spec:
      containers:
      - name: "brokerclient"
        image: simplepremium.azurecr.io/brokerclient
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: COSMOSDB_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: my-cosmosdb-secret
                key: primarykey
          - name: COSMOSDB_URL
            valueFrom:
              secretKeyRef:
                name: my-cosmosdb-secret
                key: uri
      imagePullSecrets:
      - name: simplepremiumkey
  